### ISSUE TITLE
clean up inputHandler

### ISSUE THREAD

**Issue by ebuchman** [rigelrozanski/passwerk#1]
- instead of a big block, return if the condition is not true, then do the logic, https://github.com/rigelrozanski/passwerk/blob/master/passwerk_TMSP/passwerk_TMSP.go#L215
- https://github.com/rigelrozanski/passwerk/blob/master/passwerk_TMSP/passwerk_TMSP.go#L230 is insane, why not just `URL_optionText = urlStringSplit[0]` etc.
- generalize ERROR_general conditional into a function like `checkOperation(operationalOption string, urlString ... string) string` where the `...` implies variable number of arguments (https://github.com/rigelrozanski/passwerk/blob/master/passwerk_TMSP/passwerk_TMSP.go#L258)
- use `\n` https://github.com/rigelrozanski/passwerk/blob/master/passwerk_TMSP/passwerk_TMSP.go#L299
- use `path.Join` https://github.com/rigelrozanski/passwerk/blob/master/passwerk_TMSP/passwerk_TMSP.go#L350

**Comment by rigelrozanski** [comment]
All comments addressed and merged into Master. Great ideas (thanks). Couldn't stop laughing at your second bullet, but then realized that needs to stay as it is because urlStringSplit has a variable length aka performing the declarations within loop+switch is required to avoid array out of bounds errors.

**Comment by ebuchman** [comment]
I see because `len(urlStringSplit)` may be less than `4`.
You can also use this construction:

```
for i, piece := range urlStringSplit{
}
```

to range over the elements directly.

**Comment by ebuchman** [comment]
Another option is to pre-allocate urlStringSplit as `[4]string` and `Split` into that, then you don't need the loop/case
