### ISSUE TITLE
passwords list should use a map

### ISSUE THREAD

**Issue by ebuchman** [rigelrozanski/passwerk#3]
Using a map instead of an array will allow you to avoid looping over everything to find what you want ie. https://github.com/rigelrozanski/passwerk/blob/master/passwerk_TMSP/passwerk_TMSP.go#L414

**Comment by rigelrozanski** [comment]
Would implementation of the merkle-tree as data storage from the main array solve this?

**Comment by rigelrozanski** [comment]
Open up separate Merkle-tree's for each user account when loading / use the same db as the momma db merkle-tree... add some unique identifier to all the keys in the baby merkle tree keys to prevent collisions within the database
