### ISSUE TITLE
use NaCl instead of home rolled crypto

### ISSUE THREAD

**Issue by ebuchman** [rigelrozanski/passwerk#5]
Always better to trust the experts: https://godoc.org/golang.org/x/crypto/nacl/box

**Comment by rigelrozanski** [comment]
Okay, just catching up here. Think I found a relevant example: https://play.golang.org/p/iAb__BsSai
Are you suggesting replacing the hashing funcionality (aka what is used for the master u/p) or the encryption/decryption functionality (aka for the Identifier and Saved Password). If you are referring to replacing the encryption/decryption mechanism, I'm a little bit confused as to how one would open a box without storing a private key... unless the private key was hidden as the inputs to the hash (as is currently done). Thoughts?

**Comment by ebuchman** [comment]
Yeh I was just referring to the `encrypt` function. AES alone doesnt authenticate the message, so you don't know that you're decrypting the right thing until your try. nacl/box does the auth for you. I believe you can just use the `AfterPrecomputation` methods with the key you're currently using for `sharedKey` and not worry about priv/pub stuff. I'm not sure whats best for the relationship between that key and the user password, so lets leave it for now as the hash of that junk.
