### ISSUE TITLE
AppendTx can't assume tx is valid

### ISSUE THREAD

**Issue by ebuchman** [rigelrozanski/passwerk#6]
A malicious proposer could include an invalid tx, which would currently cause your app to panic due to out-of-bounds indexing of arrays. You need to run the checktx login in appendtx as well, just in case

**Comment by rigelrozanski** [comment]
merged into master

**Comment by ebuchman** [comment]
Cool. note you can close issues with commit messages: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by rigelrozanski** [comment]
gr8 tip
