### ISSUE TITLE
Clearer separation between the tendermint driven app and the user driven app

### ISSUE THREAD

**Issue by ebuchman** [rigelrozanski/passwerk#7]
It should be clearer from the file/package layout that some code only runs on a particular users machine (anything handling cleartext) and some runs on the tendermint network. The user can be part of the tendermint network, but shouldn't have to be

**Comment by rigelrozanski** [comment]
Use locks when accessing the the app

**Comment by rigelrozanski** [comment]
define struct demonstrating that the UI is only using the app state merkle tree in read only mode
